In [11]:
# Change working directory to C://Practicuum Project 2//BBCTextClassification
import os
os.chdir('C://Practicuum Project 2//BBCTextClassification')
print(os.getcwd())

C:\Practicuum Project 2\BBCTextClassification


In [3]:
pip install kaggle

  Created wheel for kaggle: filename=kaggle-1.5.6-cp37-none-any.whl size=72864 sha256=6e18914da9b4d5104bf7da2a2dc8f99a90926a2f3596a3f2cd66f7b8231a043b
  Stored in directory: C:\Users\tabas\AppData\Local\pip\Cache\wheels\57\4e\e8\bb28d035162fb8f17f8ca5d42c3230e284c6aa565b42b72674
  Created wheel for python-slugify: filename=python_slugify-4.0.1-py2.py3-none-any.whl size=6774 sha256=29b50a0ebc3e5390d9c99293bccfe2028ed0e208d8f2a2183f7ed8d799bec762
  Stored in directory: C:\Users\tabas\AppData\Local\pip\Cache\wheels\67\b8\ba\041548f30a6fc058c9b3f79a5b7b6aea925a15dd1e5c4992a4
Successfully built kaggle python-slugify
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [4]:
# find which python version we are using
from platform import python_version

print(python_version())

3.7.4


In [5]:
import sys
print(sys.executable)
print(sys.version)
print(sys.version_info)

C:\Users\tabas\Anaconda3\python.exe
3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)


In [2]:
import kaggle

In [4]:
pip show kaggle

Name: kaggle
Version: 1.5.6
Summary: Kaggle API
Home-page: https://github.com/Kaggle/kaggle-api
Author: Kaggle
Author-email: support@kaggle.com
License: Apache 2.0
Location: c:\users\tabas\anaconda3\lib\site-packages
Requires: requests, tqdm, certifi, python-dateutil, urllib3, python-slugify, six
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [5]:
whereis kaggle

SyntaxError: invalid syntax (<ipython-input-5-b5f6c0daa416>, line 1)

In [6]:
os.chdir('C://Users//tabas')
print(os.getcwd())

C:\Users\tabas


In [12]:
# Accept competition rules before running this command
!kaggle competitions download -c learn-ai-bbc


  0%|          | 0.00/1.85M [00:00<?, ?B/s]
 54%|#####4    | 1.00M/1.85M [00:00<00:00, 6.25MB/s]
100%|##########| 1.85M/1.85M [00:00<00:00, 7.59MB/s]


In [13]:
import zipfile
with zipfile.ZipFile("learn-ai-bbc.zip","r") as zip_ref:
    zip_ref.extractall("C://Practicuum Project 2//BBCTextClassification")

In [14]:
# load the dataset 

import numpy as np
import pandas as pd

bbc_data_test=pd.read_csv('BBC News Test.csv', ',')
bbc_data_train=pd.read_csv('BBC News Train.csv', ',')

In [15]:
bbc_data_train.head()

ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [18]:
bbc_data_train.describe

<bound method NDFrame.describe of       ArticleId                                               Text  \
0          1833  worldcom ex-boss launches defence lawyers defe...   
1           154  german business confidence slides german busin...   
2          1101  bbc poll indicates economic gloom citizens in ...   
3          1976  lifestyle  governs mobile choice  faster  bett...   
4           917  enron bosses in $168m payout eighteen former e...   
...         ...                                                ...   
1485        857  double eviction from big brother model caprice...   
1486        325  dj double act revamp chart show dj duo jk and ...   
1487       1590  weak dollar hits reuters revenues at media gro...   
1488       1587  apple ipod family expands market apple has exp...   
1489        538  santy worm makes unwelcome visit thousands of ...   

           Category  
0          business  
1          business  
2          business  
3              tech  
4          busi

In [19]:
# Check for missing values
bbc_data_train.isnull().sum()

ArticleId    0
Text         0
Category     0
dtype: int64

In [20]:
#check for empty strings

# value counts
bbc_data_train['Category'].value_counts()

sport            346
business         336
politics         274
entertainment    273
tech             261
Name: Category, dtype: int64

In [22]:
# value counts
bbc_data_test.head()

ArticleId                                               Text
0       1018  qpr keeper day heads for preston queens park r...
1       1319  software watching while you work software that...
2       1138  d arcy injury adds to ireland woe gordon d arc...
3        459  india s reliance family feud heats up the ongo...
4       1020  boro suffer morrison injury blow middlesbrough...

In [23]:
bbc_data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 735 entries, 0 to 734
Data columns (total 2 columns):
ArticleId    735 non-null int64
Text         735 non-null object
dtypes: int64(1), object(1)
memory usage: 11.6+ KB


In [25]:
# combine 2 datasets by article ID and we will use this to validate the model

bbc_data_test_labels=pd.read_csv('BBC News Sample Solution.csv', ',')

bbc_data_validate= pd.merge(bbc_data_test, bbc_data_test_labels)

In [26]:
bbc_data_validate.head()

ArticleId                                               Text       Category
0       1018  qpr keeper day heads for preston queens park r...          sport
1       1319  software watching while you work software that...           tech
2       1138  d arcy injury adds to ireland woe gordon d arc...       business
3        459  india s reliance family feud heats up the ongo...  entertainment
4       1020  boro suffer morrison injury blow middlesbrough...       politics

In [27]:
bbc_data_validate.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 735 entries, 0 to 734
Data columns (total 3 columns):
ArticleId    735 non-null int64
Text         735 non-null object
Category     735 non-null object
dtypes: int64(1), object(2)
memory usage: 23.0+ KB


In [28]:
# Check for missing values
bbc_data_validate.isnull().sum()

ArticleId    0
Text         0
Category     0
dtype: int64

In [29]:
# Perform train-test split
from sklearn.model_selection import train_test_split
X=bbc_data_train['Text']
y=bbc_data_train['Category']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [30]:
# Perform feature extraction 
from sklearn.feature_extraction.text import CountVectorizer
# create an instance of the CountVectorizer
bbc_countVec=CountVectorizer()

# fit the Vectorizer to data which will then build a Vocabulary, count the number of words etc
#bbc_countVec.fit(X_train)
#X_train_count=bbc_countVec.transform(X_train)

# Transform the original text message to the vector

#both steps fit and transform above can be done in one step

X_train_count=bbc_countVec.fit_transform(X_train)


In [31]:
X_train_count

<998x20875 sparse matrix of type '<class 'numpy.int64'>'
	with 200252 stored elements in Compressed Sparse Row format>

In [32]:
X_train.shape

(998,)

In [33]:
X_train_count.shape

(998, 20875)

In [34]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer=TfidfTransformer()

In [35]:
X_train_tfidf=tfidf_transformer.fit_transform(X_train_count)

In [36]:
X_train_tfidf.shape

(998, 20875)

In [37]:
# sklearn also has a tfidf transformation function that combines the above 2 steps
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
X_train_tfidf=vectorizer.fit_transform(X_train)

In [38]:
# Train a classifier 
from sklearn.svm import LinearSVC
clf= LinearSVC()
clf.fit(X_train_tfidf,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [39]:
# We can also combine all the steps into a Pipeline object
from sklearn.pipeline import Pipeline
text_clf=Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])
text_clf.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
               

In [40]:
predictions =text_clf.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[114   0   2   0   1]
 [  1  87   0   0   0]
 [  2   1  88   0   2]
 [  0   0   0 110   0]
 [  1   1   0   0  82]]
               precision    recall  f1-score   support

     business       0.97      0.97      0.97       117
entertainment       0.98      0.99      0.98        88
     politics       0.98      0.95      0.96        93
        sport       1.00      1.00      1.00       110
         tech       0.96      0.98      0.97        84

     accuracy                           0.98       492
    macro avg       0.98      0.98      0.98       492
 weighted avg       0.98      0.98      0.98       492



In [41]:
from sklearn import metrics
metrics.accuracy_score(y_test,predictions)

0.9776422764227642

In [71]:
#let use this to predict on a message from Validate
pred_validate=text_clf.predict([bbc_data_validate['Text'][12]])

In [72]:
bbc_data_validate['Text'][12]

'blunkett tells of love and pain david blunkett has spoken of his love for married publisher kimberly quinn for the first time.  the home secretary described how it affected his friends and personal life  but said he was a great believer in personal responsibility. mr blunkett is taking legal action to gain access to mrs quinn s two-year-old son. she denies he is mr blunkett s. the interview with bbc radio sheffield was made before allegations he fast-tracked a visa for mrs quinn s nanny. the allegations  which he has denied  are being investigated by sir alan budd. mr blunkett talked about how he fell in love - but that she resisted his desire to go public.  in an apparent reference to his court action to gain access to her son  he says he was a great believer in responsibility and consequences  even when they were painful. mr blunkett told bbc radio sheffield:  i fell in love with someone and they wouldn t go public and things started to go very badly wrong in the summer  and then th

In [73]:
pred_validate

array(['politics'], dtype=object)

In [75]:
bbc_data_validate['Category'][0]

'sport'

In [53]:
X_test.head()

941    wal-mart is sued over rude lyrics the parents ...
297    howard taunts blair over splits tony blair s f...
271    fox attacks blair s tory  lies  tony blair lie...
774    online commons to spark debate online communit...
420    piero gives rugby perspective bbc sport unveil...
Name: Text, dtype: object

In [45]:
bbc_data_validate['Category'][1]

'tech'

In [55]:
X_validate=bbc_data_validate['Text'][0:734]

In [77]:
#let use this to predict on a message from Validate
pred_validate=text_clf.predict(X_validate)

In [57]:
y_validate=bbc_data_validate['Category'][0:734]

In [58]:
print(confusion_matrix(y_validate,pred_validate))
print(classification_report(y_validate,pred_validate))

[[34 21 26 37 29]
 [37 22 33 29 26]
 [29 28 23 36 30]
 [40 20 25 34 28]
 [34 24 37 29 23]]
               precision    recall  f1-score   support

     business       0.20      0.23      0.21       147
entertainment       0.19      0.15      0.17       147
     politics       0.16      0.16      0.16       146
        sport       0.21      0.23      0.22       147
         tech       0.17      0.16      0.16       147

     accuracy                           0.19       734
    macro avg       0.18      0.19      0.18       734
 weighted avg       0.18      0.19      0.18       734



In [78]:
metrics.accuracy_score(y_validate,pred_validate)

0.18528610354223432